---
- name: Make directory if DNE
  file:
    path: /opt/filerun
    state: directory
  when: filerun is defined and filerun

- name: Template configuration
  template:
    src: files/docker-compose.yaml
    dest: /opt/filerun/docker-compose.yaml
  when: filerun is defined and filerun

- name: Create required directories
  file:
    path: /opt/filerun/user-files
    state: directory
  when: filerun is defined and filerun

- name: Get data content
  include_role:
    name: nfs
  vars:
    nfs_address: store.hiroyagojo.com
    nfs_source: /volume1/Electro
    nfs_dest: /opt/filerun/user-files/Electro
  when: filerun is defined and filerun

- name: Run filerun
  docker_compose:
    project_src: /opt/filerun
    restarted: true
  when: filerun is defined and filerun