---
- name: Install chef server
  apt:
    deb: "{{ chef_server_download_url }}"
    state: present
    update_cache: true
  become: true

- name: Copy chef-server.rb
  copy:
    src: files/chef-server.rb
    dest: /etc/opscode/chef-server.rb
  become: true

- name: Reconfigure chef server
  shell:
    cmd: chef-server-ctl reconfigure
  become: true

- name: Check if admin exists
  shell:
    cmd: chef-server-ctl user-list
  register: user_list
  changed_when: false
  become: true

- name: Store if admin exists
  set_fact:
    admin_exists: "{{ chef_admin.username in user_list.stdout }}"

- name: Create new admin user
  block:
  - name: Create user
    shell:
      cmd: "chef-server-ctl user-create {{ chef_admin.username }} \
        {{ chef_admin.first }} {{ chef_admin.last }} \
        {{chef_admin.email }} {{ chef_admin.password }} \
        --filname \"{{ home_path }}/{{ chef_admin_fname }}\""
    become: true

  - name: Add admin privileges
    shell:
      cmd: "chef-server-ctl grant-server-admin-permissions {{ chef_admin.username }}"
    become: true
  when: not admin_exists

- name: Check if org exists
  shell:
    cmd: chef-server-ctl org-list
  register: org_list
  changed_when: false
  become: true

- name: Store if org exists
  set_fact:
    org_exists: "{{ chef_org in org_list.stdout }}"

- name: Create org
  shell:
    cmd: "chef-server-ctl org-create {{ chef_org }} {{ chef_org | capfirst }} \
      --association_user {{ chef_admin.username }} \
      --filename \"{{ home_path }}/{{ chef_org_fname }}\""
  when: not org_exists
  become: true
