---
- name: Maintenance
  hosts: servers
  become: true

  tasks:
  - name: Maintain packages
    apt:
      force_apt_get: true
      upgrade: dist
      update_cache: true
      cache_valid_time: 3600
      autoremove: true
      autoclean: true

  - name: Check for firmware upgrade
    shell:
      cmd: fwupdmgr get-updates -y
    register: firmware_updates_output
    changed_when: false
    failed_when: false

  - name: Check output of firmware upgrade
    set_fact:
      firmware_upgrade_needed: "{{ firmware_updates_output.rc == 0 }}"

  - name: Run firmware update
    shell:
      cmd: fwupdmgr update -y --no-reboot-check
    when: firmware_upgrade_needed

  - name: Wait if firmware update was needed
    wait_for_connection:
      delay: 60
      timeout: 300
    when: firmware_upgrade_needed

  - name: Check if a reboot is needed
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - include_tasks: tasks/reboot.yaml
    when: reboot_required_file.stat.exists
