---
- name: Install software for servers
  hosts: servers

  tasks:
  - name: Install docker
    include_role:
      name: docker
      apply:
        tags: ['docker']
    tags: ['docker']

  - name: Install kubernetes
    include_role:
      name: kubernetes
      apply:
        tags: ['kubernetes']
    tags: ['kubernetes']
