apiVersion: apps/v1
kind: Deployment
metadata:
  name: filerun-deployment
spec:
  selector:
    matchLabels:
      app: filerun-deployment
  template:
    metadata:
      labels:
        app: filerun-deployment
    spec:
      containers:
      - name: filerun-web
        image: filerun/filerun:latest
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: APACHE_RUN_USER
          value: www-data
        - name: APACHE_RUN_USER_ID
          value: "33"
        - name: APACHE_RUN_GROUP
          value: www-data
        - name: APACHE_RUN_GROUP_ID
          value: "33"
        - name: FR_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: filerun-configmap
              key: database-host
        - name: FR_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: filerun-configmap
              key: database-port
        - name: FR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: filerun-configmap
              key: database-name
        - name: FR_DB_USER
          valueFrom:
            configMapKeyRef:
              name: filerun-configmap
              key: database-user
        - name: FR_DB_PASS
          valueFrom:
            secretKeyRef: 
              name: filerun-secret
              key: database-pass
        volumeMounts:
        - mountPath: /var/www/html
          name: filerun-html-volume
        - mountPath: /user-files
          name: filerun-user-volume
        - mountPath: /user-files/Electro
          name: filerun-electro-volume

      - name: filerun-db
        image: mariadb:10.1
        ports:
        - name: mysql
          containerPort: 3306
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: false
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: filerun-configmap
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: filerun-configmap
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: filerun-secret
              key: database-pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: filerun-secret
              key: database-root-pass
        - name: TZ
          value: 'America/Los_Angeles'
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: filerun-db-volume

      volumes:
      - name: filerun-html-volume
        nfs:
          server: store.hiroyagojo.com
          path: /volume1/Containers/apps/filerun/html
      - name: filerun-user-volume
        nfs:
          server: store.hiroyagojo.com
          path: /volume1/Containers/apps/filerun/user-files
      - name: filerun-db-volume
        nfs:
          server: store.hiroyagojo.com
          path: /volume1/Containers/apps/filerun/db
      - name: filerun-electro-volume
        nfs:
          server: store.hiroyagojo.com
          path: /volume1/Electro
