title: "Puff's Homelab"
subtitle: "Welcome!"
theme: default

links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/HiDoYa"

  - name: "Portfolio"
    icon: "fas fa-book"
    url: "https://portfolio.hiroyagojo.com"

services:
  - name: "Application"
    icon: "fas fa-code-branch"
    items:
      - name: "Filerun"
        logo: "assets/images/filerun.png"
        subtitle: "File browser"
        url: "http://filerun.svc.hiroyagojo.com"

      - name: "Mango"
        logo: "assets/images/mango.png"
        subtitle: "Image browser"
        url: "http://mango.svc.hiroyagojo.com"

  - name: "Infra"
    icon: "fas fa-microchip"
    items:
      - name: "Vault"
        logo: "assets/images/vault.png"
        subtitle: "Secrets manager"
        url: "http://vault.svc.hiroyagojo.com"

      - name: "Consul"
        logo: "assets/images/consul.png"
        subtitle: "Service mesh"
        url: "http://consul.svc.hiroyagojo.com"

      - name: "Synology NFS"
        logo: "assets/images/synology.png"
        subtitle: "File storage"
        url: "http://store.hiroyagojo.com"

  - name: "Networking"
    icon: "fas fa-heartbeat"
    items:
      - name: "Pi-hole"
        logo: "assets/images/pihole.png"
        subtitle: "DNS Ad Blocker"
        url: "http://rasp1.hiroyagojo.com/admin"

      - name: "Traefik"
        logo: "assets/images/traefik.png"
        subtitle: "Web proxy"
        url: "http://traefik-admin.svc.hiroyagojo.com"

      - name: "Opnsense"
        logo: "assets/images/opnsense.png"
        subtitle: "Network firewall"
        url: "http://hiroyagojo.com"

      - name: "Unifi Dream Machine"
        logo: "assets/images/unifi.png"
        subtitle: "Wireless access point"
        url: "http://udm.hiroyagojo.com"
  
