---
chef_server_version: 15.0.9
chef_server_download_url: "https://packages.chef.io/files/stable/chef-server/{{ chef_server_version }}/ubuntu/20.04/chef-server-core_{{ chef_server_version }}-1_amd64.deb"

chef_client_version: 17.10.3
chef_client_download_url: "https://packages.chef.io/files/stable/chef/{{ chef_client_version }}/ubuntu/20.04/chef_{{ chef_client_version }}-1_amd64.deb"

chef_org: homelab
chef_org_fname: "chef-org-{{ chef_org }}-validator.pem"

chef_admin:
  username: admin
  first: hiroya
  last: gojo
  email: hiroyagojo@gmail.com
  password: NONE
chef_admin_fname: "chef-user-{{ chef_admin.username }}.pem"

chef_workstation_path: "/Users/hiroya.gojo/.chef-personal"
