---
- name: Run mango
  docker_container: 
    name: mango
    image: hkalexling/mango
    detach: true
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - /opt/mango/data:/root/mango
      - /opt/mango/config:/root/.config/mango
  when: mango is defined and mango

- name: Get data content
  include_role:
    name: nfs
  vars:
    nfs_address: store.hiroyagojo.com
    nfs_source: /volume1/Electro/Pictures/Manga
    nfs_dest: /opt/mango/data/library
  when: mango is defined and mango
