providers:
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

api:
  insecure: true
  dashboard: true

# Temporary Static config
# This should change to dynamic config using consul service discovery

http:
  routers: 
    mango-router:
      rule: Host(`mango.svc.hiroyagojo.com`)
      service: mango-service
      middlewares:
        - auth
    consul-router:
      rule: Host(`consul.svc.hiroyagojo.com`)
      service: consul-service
      middlewares:
        - auth
    pihole-router:
      rule: Host(`pihole.svc.hiroyagojo.com`)
      service: pihole-service
      middlewares:
        - auth
    traefik-admin-router:
      rule: Host(`traefik-admin.svc.hiroyagojo.com`)
      service: traefik-admin-service
      middlewares:
        - auth

  middlewares:
    auth:
      basicAuth:
        users:
          - "{{ admin_htpass }}"

  services:
    mango-service:
      loadBalancer:
        servers:
        - url: "http://node2.hiroyagojo.com:9000"
    consul-service:
      loadBalancer:
        servers:
        - url: "http://node1.hiroyagojo.com:8500"
    pihole-service:
      loadBalancer:
        servers:
        - url: "http://rasp1.hiroyagojo.com"
    traefik-admin-service:
      loadBalancer:
        servers:
        - url: "http://node2.hiroyagojo.com:8080"