version: '2'

services:
  filerun_db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_filerun_database }}"
      MYSQL_USER: "{{ mysql_filerun_username }}"
      MYSQL_PASSWORD: "{{ mysql_filerun_password }}"
    volumes:
      - ./db:/var/lib/mysql
    restart: always

  filerun_web:
    image: filerun/filerun
    environment:
      FR_DB_HOST: filerun_db
      FR_DB_PORT: 3306
      FR_DB_NAME: "{{ mysql_filerun_database }}"
      FR_DB_USER: "{{ mysql_filerun_username }}"
      FR_DB_PASS: "{{ mysql_filerun_password }}"
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerun_db
    links:
      - filerun_db:db
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
      - ./user-files:/user-files
    restart: always
