version: '2'

services:
  filerun_db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_FILERUN_DATABASE }}"
      MYSQL_USER: "{{ MYSQL_FILERUN_USERNAME }}"
      MYSQL_PASSWORD: "{{ MYSQL_FILERUN_PASSWORD }}"
    volumes:
      - ./db:/var/lib/mysql

  filerun_web:
    image: filerun/filerun
    environment:
      FR_DB_HOST: filerun_db
      FR_DB_PORT: 3306
      FR_DB_NAME: "{{ MYSQL_FILERUN_DATABASE }}"
      FR_DB_USER: "{{ MYSQL_FILERUN_USERNAME }}"
      FR_DB_PASS: "{{ MYSQL_FILERUN_PASSWORD }}"
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerun_db
    links:
      - filerun_db:db
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
      - ./user-files:/user-files
