---
- name: Shutdown servers
  hosts: servers
  become: true

  tasks:
    - name: Shutdown servers
      community.general.shutdown:
        msg: "Ansible triggered shutdown"
      when: not(node is defined and inventory_hostname not in node)
