---
- name: Make directory if DNE
  file:
    path: /opt/traefik
    state: directory
  when: traefik is defined and traefik

- name: Template configuration
  template:
    src: files/traefik.yaml
    dest: /opt/traefik/traefik.yaml
  when: traefik is defined and traefik

- name: Run traefik
  docker_container: 
    name: traefik
    image: traefik:latest
    detach: true
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes: 
      - /opt/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: true
  when: traefik is defined and traefik
