---
- name: Initialize systems
  hosts: servers,rasps
  become: true

  roles:
  - ssh

  tasks:
  - name: Ensure group "wheel" exists
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers users to wheel group
    user:
      name: ubuntu
      groups: wheel
      append: true
      state: present
      createhome: true

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Add nfs to scratch storage 
    include_role:
      name: nfs
    vars:
      nfs_address: store.hiroyagojo.com
      nfs_source: /volume1/Scratch
      nfs_dest: /home/ubuntu/Scratch