---
- name: Install software for servers
  hosts: servers,rasps
  become: true
  tasks:
  - name: Install docker
    include_role:
      name: docker
      apply:
        tags: ['docker']
    tags: ['docker']

- name: Install software for dell servers
  hosts: servers
  become: true
  tasks:
  - name: Install consul
    include_role:
      name: consul
      apply:
        tags: ['consul']
    tags: ['consul']
