---
- name: Install software for servers
  hosts: servers,rasps
  become: true
  tasks:
  - name: Install docker
    include_role:
      name: docker
      apply:
        tags: ['docker']
    tags: ['docker']

- name: Install software for raspberry pi server
  hosts: rasps
  become: true
  tasks:
  - name: Install pihole
    include_role:
      name: pihole
      apply:
        tags: ['pihole']
    tags: ['pihole']

- name: Install software for dell servers
  hosts: servers
  become: true
  tasks:
  - name: Install consul
    include_role:
      name: consul
      apply:
        tags: ['consul']
    tags: ['consul']

  - name: Install chef
    include_role:
      name: chef
      apply:
        tags: ['chef']
    tags: ['chef']

  - name: Install traefik
    include_role:
      name: traefik
      apply:
        tags: ['traefik']
    tags: ['traefik']

  - name: Install mango
    include_role:
      name: mango
      apply:
        tags: ['mango']
    tags: ['mango']

  - name: Install filerun
    include_role:
      name: filerun
      apply:
        tags: ['filerun']
    tags: ['filerun']
