--- 
- name: Startup
  hosts: raspis
  become: true

  tasks:
  - name: Startup
    uri:
      url: https://raw.githubusercontent.com/jpoliv/wakeonlan/master/wakeonlan
      dest: /usr/local/bin/wakeonlan
      mode: "755"

  - name: Get MAC Addresses
    set_fact:
      mac_addresses: "{{ mac_addresses | default([]) + [hostvars[item].mac] }}"
    with_items: "{{ groups['servers'] }}"

  - name: Startup
    shell:
      cmd: "wakeonlan {{ item }}"
    with_items: mac_addresses

    