---
- name: Copy docker compose
  template:
    src: files/docker-compose.yml.j2
    dest: /opt/pihole/docker-compose.yml

- name: Run docker compose
  docker_compose: 
    project_src: /opt/pihole

- name: Create DNS file
  template:
    src: files/custom.list.j2
    dest: /opt/pihole/etc-pihole/custom.list

- name: Ensure sqlite3 is installed
  apt:
    name: sqlite3
    update_cache: true

